# Trading Configuration
trading:
  # Position sizing options (percentage of available balance)
  position_sizes: [5, 10, 15, 20, 25]
  
  # Risk management
  max_daily_loss_percent: 10
  max_position_loss_percent: 5
  emergency_stop_loss_percent: 15
  
  # Monitoring intervals
  price_check_interval_minutes: 15
  news_check_interval_minutes: 60
  
  # Trading pairs to consider
  allowed_pairs: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "ADAUSDT", "DOTUSDT", "DOGEUSDT", "AVAXUSDT"]
  
  # Session settings
  max_trades_per_day: 3
  cooldown_between_trades_minutes: 30

# AWS Bedrock Configuration
bedrock:
  # region, model_id, and fallback_model_id can be overridden by environment variables
  # BEDROCK_REGION, BEDROCK_MODEL_ID, BEDROCK_FALLBACK_MODEL_ID
  max_tokens: 4000
  temperature: 0.1
  # Authentication method (set use_api_key: true to use Bedrock API key)
  use_api_key: false  # Set to true for API key auth, false for AWS credentials

# Bybit Configuration
# All Bybit settings are loaded from environment variables:
# BYBIT_TESTNET, BYBIT_CATEGORY, BYBIT_DEMO_MODE, BYBIT_API_KEY, BYBIT_API_SECRET

# News Sources Configuration
news:
  sources:
    - name: "coindesk"
      enabled: true
      weight: 0.3
    - name: "cryptocompare"
      enabled: true
      weight: 0.25
    - name: "fear_greed_index"
      enabled: true
      weight: 0.2
    - name: "social_sentiment"
      enabled: true
      weight: 0.25

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/trading.log"
  max_file_size_mb: 10
  backup_count: 5

# Database Configuration
database:
  path: "data/trades.db"
  backup_interval_hours: 24
